apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_HOST: YXBwb2ludG1lbnQtbXlzcWwuY2VmdWNleWllaXEyLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  DB_USER: YWRtaW4=
  DB_PASS: RnIxNU0waU9iOls8
  DB_NAME: YXBwX2Ri
